### ISSUE TITLE
`unique2` branch interupting UI

### ISSUE THREAD

**Issue by lynns** [marcoarment/FCModel#127]
I've been trying out the new `unique2` branch and I noticed that you chose to synchronize all db interactions on the UI thread.  While it seems to work fine for reading/writing data, if I have much data processing going on then my UI starts hanging.  It's especially noticeable if I'm scrolling things while the background processing is happening.  Is there a reason you chose to synchronize on the main thread rather than on a custom serial dispatch queue?  Have you seen this problem?  Any thoughts on how to best load data in the background without interrupting the UI?

**Comment by marcoarment** [comment]
Serializing all database access on the main thread in `unique2` is intentional, accepting the risk of short UI delays in extreme circumstances, with the intent that these cases are rare for FCModel-based applications.

I chose to do this for two reasons:

1. It greatly reduces bug potential — not in FCModel, but in the calling app.
2. With the previous custom-serial-queue design, big database operations usually blocked the UI anyway, as the UI tried to run a short query and got blocked by the big background operation.

Since the lockless UI rarely happened in practice, I chose to take the simplicity and bug-reduction benefits of putting all operations on the main thread.

With either design, as long as database access is on a serial queue, it's best to rework any large operations to either not be necessary, be performed in chunks, use indexes more efficiently, or not use FCModel.
